insert into courses (course_name, course_description) values ('Math', 'Mathematics Course');
insert into courses (course_name, course_description) values ('Biology', 'Biology Course');
insert into courses (course_name, course_description) values ('History', 'History Course');
insert into courses (course_name, course_description) values ('Physics', 'Physics Course');
insert into courses (course_name, course_description) values ('Chemistry', 'Chemistry Course');
insert into courses (course_name, course_description) values ('Computer Science', 'Computer Science Course');
insert into courses (course_name, course_description) values ('Art', 'Art Course');
insert into courses (course_name, course_description) values ('Literature', 'Literature Course');
insert into courses (course_name, course_description) values ('Music', 'Music Course');
insert into courses (course_name, course_description) values ('Geography', 'Geography Course');
